services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server: 
    build: ./server
    secrets:
      - openai_api_key
    environment:
      - PROD=true
      - PATH=/run/secrets/openai_api_key
    env_file:
      - './server/res/.env'
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

      
secrets:
  openai_api_key:
    file: ./server/res/OPENAI_API_KEY.txt