import { Providers } from '../app/providers'
import { fonts } from '../app/fonts'
import "./globals.css"
import theme from '../app/theme'
import Nav from '../components/Nav'
import Breadcrumbs from '../components/Breadcrumbs'
import SideBar from "../components/Sidebar"
import Head from 'next/head'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: "QuickStudyGPT",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
    return (
        <html lang='en'>
            <body className="h-screen bg-stone-900">
                <Nav />
                <Providers>
                    <div className="grid grid-flow-row grid-cols-6 h-screen">
                        <div className="col-span-1">
                            <SideBar />
                        </div>
                        <div className="col-span-5">
                            {children}
                        </div>
                    </div>
                </Providers>
                
            </body>
        </html>
    )
}